### ISSUE TITLE
Set proxy server

### ISSUE THREAD

**Issue by peter279k** [Porter-connectors/HttpConnector#8]
As title, is it possible to set the proxy server before sending the HTTP requests?
If possible, can @Bilge provide the proxy server setting like the ```.travis.yml``` fle?

Thanks.

**Comment by Bilge** [comment]
https://github.com/Porter-connectors/HttpConnector/blob/7448356317572feec8b828d4e69f1c04a6b656d8/src/Net/Http/HttpOptions.php#L170-L173
